## Common Ariane XDCs

create_clock -period 100.000 -name tck -waveform {0.000 50.000} [get_ports tck]
set_input_jitter tck 1.000
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets tck_IBUF]

# minimize routing delay
set_input_delay -clock tck -clock_fall 5.000 [get_ports tdi]
set_input_delay -clock tck -clock_fall 5.000 [get_ports tms]
set_output_delay -clock tck 5.000 [get_ports tdo]
set_false_path -from [get_ports trst_n]


set_max_delay -datapath_only -from [get_pins i_dmi_jtag/i_dmi_cdc/i_cdc_resp/i_src/data_src_q_reg*/C] -to [get_pins i_dmi_jtag/i_dmi_cdc/i_cdc_resp/i_dst/data_dst_q_reg*/D] 20.000
set_max_delay -datapath_only -from [get_pins i_dmi_jtag/i_dmi_cdc/i_cdc_resp/i_src/req_src_q_reg/C] -to [get_pins i_dmi_jtag/i_dmi_cdc/i_cdc_resp/i_dst/req_dst_q_reg/D] 20.000
set_max_delay -datapath_only -from [get_pins i_dmi_jtag/i_dmi_cdc/i_cdc_req/i_dst/ack_dst_q_reg/C] -to [get_pins i_dmi_jtag/i_dmi_cdc/i_cdc_req/i_src/ack_src_q_reg/D] 20.000

# set multicycle path on reset, on the FPGA we do not care about the reset anyway
set_multicycle_path -from [get_pins {i_rstgen_main/i_rstgen_bypass/synch_regs_q_reg[3]/C}] 4
set_multicycle_path -hold -from [get_pins {i_rstgen_main/i_rstgen_bypass/synch_regs_q_reg[3]/C}] 3



connect_debug_port u_ila_0/probe0 [get_nets [list {i_ariane/commit_stage_i/nop_thingy/prev_entry[bp][cf][0]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[bp][cf][1]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[bp][cf][2]}]]
connect_debug_port u_ila_0/probe1 [get_nets [list {i_ariane/commit_stage_i/nop_thingy/prev_entry[bp][predict_address][0]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[bp][predict_address][1]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[bp][predict_address][2]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[bp][predict_address][3]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[bp][predict_address][4]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[bp][predict_address][5]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[bp][predict_address][6]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[bp][predict_address][7]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[bp][predict_address][8]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[bp][predict_address][9]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[bp][predict_address][10]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[bp][predict_address][11]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[bp][predict_address][12]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[bp][predict_address][13]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[bp][predict_address][14]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[bp][predict_address][15]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[bp][predict_address][16]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[bp][predict_address][17]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[bp][predict_address][18]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[bp][predict_address][19]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[bp][predict_address][20]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[bp][predict_address][21]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[bp][predict_address][22]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[bp][predict_address][23]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[bp][predict_address][24]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[bp][predict_address][25]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[bp][predict_address][26]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[bp][predict_address][27]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[bp][predict_address][28]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[bp][predict_address][29]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[bp][predict_address][30]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[bp][predict_address][31]}]]
connect_debug_port u_ila_0/probe2 [get_nets [list {i_ariane/commit_stage_i/nop_thingy/prev_entry[ex][cause][0]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[ex][cause][1]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[ex][cause][2]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[ex][cause][3]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[ex][cause][4]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[ex][cause][5]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[ex][cause][6]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[ex][cause][7]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[ex][cause][8]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[ex][cause][9]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[ex][cause][10]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[ex][cause][11]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[ex][cause][12]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[ex][cause][13]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[ex][cause][14]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[ex][cause][15]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[ex][cause][16]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[ex][cause][17]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[ex][cause][18]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[ex][cause][19]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[ex][cause][20]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[ex][cause][21]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[ex][cause][22]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[ex][cause][23]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[ex][cause][24]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[ex][cause][25]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[ex][cause][26]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[ex][cause][27]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[ex][cause][28]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[ex][cause][29]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[ex][cause][30]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[ex][cause][31]}]]
connect_debug_port u_ila_0/probe3 [get_nets [list {i_ariane/commit_stage_i/nop_thingy/prev_entry[ex][tval][0]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[ex][tval][1]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[ex][tval][2]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[ex][tval][3]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[ex][tval][4]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[ex][tval][5]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[ex][tval][6]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[ex][tval][7]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[ex][tval][8]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[ex][tval][9]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[ex][tval][10]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[ex][tval][11]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[ex][tval][12]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[ex][tval][13]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[ex][tval][14]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[ex][tval][15]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[ex][tval][16]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[ex][tval][17]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[ex][tval][18]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[ex][tval][19]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[ex][tval][20]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[ex][tval][21]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[ex][tval][22]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[ex][tval][23]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[ex][tval][24]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[ex][tval][25]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[ex][tval][26]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[ex][tval][27]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[ex][tval][28]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[ex][tval][29]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[ex][tval][30]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[ex][tval][31]}]]
connect_debug_port u_ila_0/probe4 [get_nets [list {i_ariane/commit_stage_i/nop_thingy/prev_entry[fu][0]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[fu][1]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[fu][2]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[fu][3]}]]
connect_debug_port u_ila_0/probe5 [get_nets [list {i_ariane/commit_stage_i/nop_thingy/prev_entry[op][0]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[op][1]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[op][2]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[op][3]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[op][4]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[op][5]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[op][6]}]]
connect_debug_port u_ila_0/probe6 [get_nets [list {i_ariane/commit_stage_i/nop_thingy/prev_entry[pc][0]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[pc][1]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[pc][2]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[pc][3]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[pc][4]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[pc][5]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[pc][6]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[pc][7]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[pc][8]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[pc][9]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[pc][10]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[pc][11]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[pc][12]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[pc][13]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[pc][14]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[pc][15]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[pc][16]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[pc][17]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[pc][18]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[pc][19]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[pc][20]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[pc][21]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[pc][22]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[pc][23]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[pc][24]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[pc][25]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[pc][26]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[pc][27]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[pc][28]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[pc][29]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[pc][30]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[pc][31]}]]
connect_debug_port u_ila_0/probe7 [get_nets [list {i_ariane/commit_stage_i/nop_thingy/prev_entry[rd][0]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[rd][1]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[rd][2]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[rd][3]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[rd][4]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[rd][5]}]]
connect_debug_port u_ila_0/probe8 [get_nets [list {i_ariane/commit_stage_i/nop_thingy/prev_entry[result][0]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[result][1]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[result][2]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[result][3]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[result][4]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[result][5]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[result][6]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[result][7]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[result][8]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[result][9]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[result][10]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[result][11]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[result][12]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[result][13]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[result][14]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[result][15]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[result][16]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[result][17]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[result][18]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[result][19]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[result][20]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[result][21]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[result][22]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[result][23]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[result][24]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[result][25]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[result][26]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[result][27]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[result][28]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[result][29]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[result][30]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[result][31]}]]
connect_debug_port u_ila_0/probe9 [get_nets [list {i_ariane/commit_stage_i/nop_thingy/prev_entry[rs1][0]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[rs1][1]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[rs1][2]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[rs1][3]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[rs1][4]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[rs1][5]}]]
connect_debug_port u_ila_0/probe10 [get_nets [list {i_ariane/commit_stage_i/nop_thingy/prev_entry[rs2][0]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[rs2][1]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[rs2][2]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[rs2][3]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[rs2][4]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[rs2][5]}]]
connect_debug_port u_ila_0/probe11 [get_nets [list {i_ariane/commit_stage_i/nop_thingy/prev_entry[trans_id][0]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[trans_id][1]} {i_ariane/commit_stage_i/nop_thingy/prev_entry[trans_id][2]}]]
connect_debug_port u_ila_0/probe13 [get_nets [list i_ariane/commit_stage_i/nop_thingy/detect_NOP]]
connect_debug_port u_ila_0/probe14 [get_nets [list i_ariane/commit_stage_i/nop_thingy/detect_prep_NOP]]
connect_debug_port u_ila_0/probe15 [get_nets [list {i_ariane/commit_stage_i/nop_thingy/prev_entry[ex][valid]}]]
connect_debug_port u_ila_0/probe16 [get_nets [list {i_ariane/commit_stage_i/nop_thingy/prev_entry[is_compressed]}]]
connect_debug_port u_ila_0/probe17 [get_nets [list {i_ariane/commit_stage_i/nop_thingy/prev_entry[use_imm]}]]
connect_debug_port u_ila_0/probe18 [get_nets [list {i_ariane/commit_stage_i/nop_thingy/prev_entry[use_pc]}]]
connect_debug_port u_ila_0/probe19 [get_nets [list {i_ariane/commit_stage_i/nop_thingy/prev_entry[use_zimm]}]]
connect_debug_port u_ila_0/probe20 [get_nets [list {i_ariane/commit_stage_i/nop_thingy/prev_entry[valid]}]]
connect_debug_port u_ila_0/probe21 [get_nets [list i_ariane/commit_stage_i/nop_thingy/prev_nop]]
connect_debug_port u_ila_0/probe22 [get_nets [list i_ariane/commit_stage_i/nop_thingy/prev_prep_nop]]
connect_debug_port u_ila_0/probe23 [get_nets [list i_ariane/commit_stage_i/nop_thingy/prev_ret]]

